# SPDX-License-Identifier: Apache-2.0
"""Split-terminal dashboard via Zellij (Rust) or tmux fallback."""

from __future__ import annotations

import os
import re
import shlex
import shutil
import subprocess
import sys
from argparse import Namespace
from pathlib import Path

from pulsing.cli.agent.helpers import DEFAULT_PROG, load_cfg
from pulsing.agent.workspace.config import WorkspaceConfig

DASHBOARD_LAYOUT = "dashboard.kdl"
DEMO_LAYOUT = "demo.kdl"
ZELLIJ_SESSION = "pulsing-agent-dashboard"
ZELLIJ_DEMO_SESSION = "pulsing-agent-demo"
TMUX_SESSION = "pulsing-agent-dashboard"
DEMO_WORKER_ENV = "PULSING_AGENT_DEMO_WORKER"


def agent_cli_argv(*args: str) -> list[str]:
    exe = shutil.which("pulsing-agent")
    if exe:
        return [exe, *args]
    return [sys.executable, "-m", "pulsing.cli.agent", *args]


def _kdl_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _follow_shell_cmd(argv: list[str], interval: float) -> str:
    cmd = " ".join(shlex.quote(part) for part in argv)
    return f"while [ ! -f .pulsing/node.json ]; do sleep 0.5; done; exec {cmd}"


def _agent_names(cfg: WorkspaceConfig) -> list[str]:
    names = [n.strip() for n in (cfg.default_agents or []) if n.strip()]
    return names or ["guide"]


def _agent_log_panes(
    agent_names: list[str],
    *,
    interval: float,
    indent: str = "        ",
) -> list[str]:
    names = [n.strip() for n in agent_names if n.strip()] or ["guide"]
    log_interval = max(0.5, interval)
    lines: list[str] = [f'{indent}pane split_direction="vertical" {{']
    inner = indent + "    "
    for name in names:
        logs = agent_cli_argv("logs", name, "-f", "-i", str(log_interval))
        run = _follow_shell_cmd(logs, log_interval)
        lines.extend(
            [
                f'{inner}pane name="{name}" command="bash" {{',
                f"    {inner}args {_kdl_str('-c')} {_kdl_str(run)}",
                f"{inner}}}",
            ],
        )
    lines.append(f"{indent}}}")
    return lines


def write_zellij_layout(
    cfg: WorkspaceConfig,
    *,
    interval: float = 0.8,
    agent_names: list[str] | None = None,
) -> Path:
    root = Path(cfg.root).resolve()
    cfg.pulsing_dir.mkdir(parents=True, exist_ok=True)
    path = cfg.pulsing_dir / DASHBOARD_LAYOUT
    names = agent_names if agent_names is not None else _agent_names(cfg)

    lines = [
        "// Generated by pulsing agent dashboard — per-agent log panes",
        "layout {",
        f"    cwd {_kdl_str(str(root))}",
        '    pane split_direction="vertical" {',
        '        pane size="70%" {',
    ]
    lines.extend(_agent_log_panes(names, interval=interval))
    lines.extend(
        [
            "        }",
            '        pane name="player" command="bash" {',
            f"            args {_kdl_str('-c')} {_kdl_str(_player_shell_hint(DEFAULT_PROG))}",
            "        }",
            "    }",
            "}",
            "",
        ],
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_zellij_demo_layout(
    cfg: WorkspaceConfig,
    *,
    demo_shell: str,
    interval: float = 0.8,
    agent_names: list[str] | None = None,
) -> Path:
    root = Path(cfg.root).resolve()
    cfg.pulsing_dir.mkdir(parents=True, exist_ok=True)
    path = cfg.pulsing_dir / DEMO_LAYOUT
    names = agent_names if agent_names is not None else _agent_names(cfg)

    lines = [
        "// Generated by pulsing agent demo — demo worker + per-agent logs",
        "layout {",
        f"    cwd {_kdl_str(str(root))}",
        '    pane split_direction="horizontal" {',
        '        pane size="38%" name="demo" command="bash" {',
        f"            args {_kdl_str('-c')} {_kdl_str(demo_shell)}",
        "        }",
    ]
    lines.extend(_agent_log_panes(names, interval=interval, indent="        "))
    lines.extend(["    }", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _player_shell_hint(prog: str) -> str:
    return (
        f"echo 'Craft player shell — run {prog} npc say <name> \"...\" here'; "
        f"echo 'Agents log in panes above; wake world: {prog} wake'; "
        "exec $SHELL"
    )


def find_backend(preferred: str = "auto") -> str:
    choice = (preferred or "auto").strip().lower()
    if choice == "zellij":
        if shutil.which("zellij"):
            return "zellij"
        raise SystemExit(
            "zellij not found — install: https://zellij.dev/documentation/installation.html "
            "(Rust multiplexer; brew install zellij)",
        )
    if choice == "tmux":
        if shutil.which("tmux"):
            return "tmux"
        raise SystemExit("tmux not found")
    if shutil.which("zellij"):
        return "zellij"
    if shutil.which("tmux"):
        return "tmux"
    raise SystemExit(
        "no split-terminal backend found.\n"
        "  Recommended: zellij (Rust) — brew install zellij\n"
        "  Fallback:    tmux — brew install tmux\n"
        "Or run: pulsing agent logs <name> -f",
    )


def _strip_ansi(text: str) -> str:
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


def _parse_zellij_session_line(line: str, session: str) -> str | None:
    """Return 'active', 'exited', or None for one ``list-sessions`` line."""
    plain = _strip_ansi(line.strip())
    if not plain:
        return None
    name = (plain.split() or [""])[0]
    if name != session:
        return None
    if "EXITED" in plain.upper():
        return "exited"
    return "active"


def _zellij_session_state(session: str) -> str | None:
    zellij = shutil.which("zellij")
    if not zellij:
        return None
    out = subprocess.run(
        [zellij, "list-sessions"],
        capture_output=True,
        text=True,
        check=False,
    )
    if out.returncode != 0:
        return None
    for line in out.stdout.splitlines():
        state = _parse_zellij_session_line(line, session)
        if state is not None:
            return state
    return None


def _zellij_delete_session(session: str) -> None:
    zellij = shutil.which("zellij")
    if not zellij:
        return
    subprocess.run(
        [zellij, "delete-session", "-f", session],
        capture_output=True,
        check=False,
    )


def _zellij_session_running(session: str) -> bool:
    return _zellij_session_state(session) == "active"


def launch_zellij(
    layout_path: Path,
    *,
    session: str = ZELLIJ_SESSION,
    attach_only: bool = False,
) -> None:
    zellij = shutil.which("zellij")
    assert zellij
    state = _zellij_session_state(session)
    if state == "active":
        os.execvp(zellij, [zellij, "attach", session])
    if state == "exited":
        _zellij_delete_session(session)
    if attach_only:
        raise SystemExit(f"no zellij session {session!r} — start it first")
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        raise SystemExit(
            "zellij needs an interactive terminal — run `pulsing agent dashboard` or `pulsing agent demo` "
            "directly in your terminal (not from a background subprocess)",
        )
    os.execvp(
        zellij,
        [zellij, "--new-session-with-layout", str(layout_path), "-s", session],
    )


def launch_tmux(
    cfg: WorkspaceConfig,
    *,
    interval: float = 0.8,
    prog: str = DEFAULT_PROG,
    agent_names: list[str] | None = None,
) -> None:
    tmux = shutil.which("tmux")
    if not tmux:
        raise SystemExit("tmux not found")

    root = str(Path(cfg.root).resolve())
    names = agent_names if agent_names is not None else _agent_names(cfg)
    log_interval = max(0.5, interval)
    hint = shlex.quote(_player_shell_hint(prog))

    pane_cmds: list[str] = []
    for name in names:
        logs = shlex.quote(
            _follow_shell_cmd(
                agent_cli_argv("logs", name, "-f", "-i", str(log_interval)),
                log_interval,
            ),
        )
        pane_cmds.append(logs)

    script_lines = [
        "set -e",
        f"if tmux has-session -t {TMUX_SESSION} 2>/dev/null; then",
        f"  exec tmux attach -t {TMUX_SESSION}",
        "fi",
        f"tmux new-session -d -s {TMUX_SESSION} -c {shlex.quote(root)} -n dash",
    ]
    if pane_cmds:
        script_lines.append(
            f"tmux send-keys -t {TMUX_SESSION}:0.0 {pane_cmds[0]} Enter"
        )
        for i, cmd in enumerate(pane_cmds[1:], start=1):
            script_lines.append(
                f"tmux split-window -h -t {TMUX_SESSION}:0 -c {shlex.quote(root)}"
            )
            script_lines.append(f"tmux send-keys -t {TMUX_SESSION}:0.{i} {cmd} Enter")
        script_lines.append(
            f"tmux split-window -v -t {TMUX_SESSION}:0 -c {shlex.quote(root)}"
        )
        player_idx = len(pane_cmds)
        script_lines.append(
            f"tmux send-keys -t {TMUX_SESSION}:0.{player_idx} {hint} Enter"
        )
        script_lines.append(f"tmux select-pane -t {TMUX_SESSION}:0.{player_idx}")
    else:
        script_lines.append(f"tmux send-keys -t {TMUX_SESSION}:0.0 {hint} Enter")
    script_lines.append(f"exec tmux attach -t {TMUX_SESSION}")
    subprocess.run(["bash", "-c", "\n".join(script_lines)], check=True)


def run_dashboard(args: Namespace, *, prog: str = DEFAULT_PROG) -> None:
    cfg = load_cfg()
    backend = find_backend(getattr(args, "backend", "auto"))
    interval = float(getattr(args, "interval", 0.8))

    if not cfg.seed_addr():
        print(
            f"note: world asleep — start `{prog} wake` or `{prog} demo` first",
            file=sys.stderr,
        )

    if backend == "zellij":
        layout = write_zellij_layout(cfg, interval=interval)
        print(f"opening Zellij dashboard ({layout})", file=sys.stderr)
        launch_zellij(layout)
        return

    print(
        "opening tmux dashboard (install zellij for Rust multiplexer)", file=sys.stderr
    )
    launch_tmux(cfg, interval=interval, prog=prog)
